hm_prct/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='authors-posts')),
    path('admin/', admin.site.urls, name='admin'),
]

posts/urls.py
from django.urls import path, include

from . import  views

app_name = 'posts'
group_patterns = ([
    path('<str:slug>/', views.group_posts, name='group'),
], 'group')

urlpatterns = [
    path('', views.index, name='index'),
    path('group/', include(group_patterns, namespace='group_url')),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.SlugField(unique=True)
    description = models.TextField()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='posts',
        blank=True,
        null=True,
    )

posts/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404

from . models import Post, Group


TEMPLATES = {
    'index': 'posts/index.html',
    'group_list': 'posts/group_list.html',
}


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, TEMPLATES['index'], context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, TEMPLATES['group_list'], context)

# Create your views here.

templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="en"> <!-- Язык сайта - русский -->
<head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static "img/fav/fav.ico" %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>{% block title %}no title{% endblock %}</title>
</head>
<body>
    <header>
        {% include 'includes/header.html' %}
    </header>
        {% block content %}
        {% endblock %}
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %}
    </footer>
</body>

templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
        </a>
    </div>
</nav>

templates/includes/post.html
<article>
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:'d M Y' }}
      </li>
    </ul>      
    <p>
        {{ post.text }}
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_url:group' post.group.slug %}">все записи группы</a>
    {% endif %}
</article>

templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <main>
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      <h1>{{ group.title }}</h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in posts %}
        <div class="single-post">
          {% include 'includes/post.html' %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </main>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <main> 
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      {% for post in posts %}
        {% include 'includes/post.html' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
      <!-- под последним постом нет линии -->
    </div>
  </main>
{% endblock %}